name: firebase_admin
description: A Cloudflare Workers function written in Dart.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  edge: ^0.0.1
  cloudflare_workers: ^0.0.1
  dart_firebase_admin:
    git:
        url: https://github.com/akaboshinit/dart_firebase_admin.git
        path: packages/dart_firebase_admin
        ref: add-Credential.fromServiceAccountParams
  edge_http_client: ^0.0.1+3
  http: ^0.13.6

dev_dependencies:
  lints: ^2.0.1
